name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=adityakhandare912@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://dl.dropboxusercontent.com/scl/fi/hr8mexihky9s6k6cemzd8/down.bat?rlkey=ow7mgkgm09znvw8lobu9unxcp&dl=0" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
